### PR TITLE
Update CLI instructions for story

### PR DESCRIPTION
**Pull request by wilzbach**
Currently it looks a bit weird though:

image

I created a separate issue for this: https://github.com/storyscript/docs.storyscript.io/issues/73, but we should probably wait with merging/deploying this until the styling looks nice.

Also the snap package doesn't exist yet, so don't merge this just yet.

### CODE REVIEW

**Comment by JeanBarriere** [comment]
@wilzbach design update indeed is needed. Will see what I can do asap.

**Comment by wilzbach** [comment]
Published `story` to the snap store (-> https://snapcraft.io/story), so we should be able to advertise it now on storyscript.io

**Comment by wilzbach** [comment]
Doesn't look too bad in the preview:

image

So I guess we can go ahead here and merge this, s.t. people get up-to-date instructions?

(of course the styling could be improved later on)

**Comment by JeanBarriere** [comment]
Well let's deploy then !

**Pull request merged**
