### PR TITLE
feat(theme+sidebar+content)

### PR DESCRIPTION
**Pull request by JeanBarriere**
- [x] improve sidebar
- [x] improve searchbar
- [x] content has been moved to a bigger domain on the menu so it makes it easier to search

**Please check the design on the netlify preview**

Note:
I've added 2 more pages, not publicly but to add plausible and future content and why we've been through these re-categorization.
_Learn_ and _Plugins_ page should appear under development. **The content of those pages is not written**.

Screenshot from 2019-06-21 16-21-42 
Screenshot from 2019-06-21 16-21-37

### CODE REVIEW

**Comment by judepereira** [comment]
The arrows in the left nav appear to be broken:
Screenshot 2019-06-24 at 11 18 59

**Comment by judepereira** [comment]
@JeanBarriere also, who will populate the Learn and Plugins page?

**Comment by JeanBarriere** [comment]
@judepereira We need someone to write this content. I can do that later or if someone is interested in that, can implement it.

Also I'm syncing with Ayda to know how to fix that size properly

**Comment by judepereira** [comment]
Also, there used to be a nice edit button which would take one directly to the GitHub page for editing the current page. That button is now missing.

**Comment by judepereira** [comment]
LGTM.

**Pull request merged**
